from pathlib import Path
import json,hashlib,unicodedata
r=Path(__file__).resolve().parents[2];e=r/'dev-docs/p4-evidence/run-20260905';f=r/'test/fixtures/recognition_acceptance'
def read(p):return json.loads(p.read_text(encoding='utf-8'))
def write(p,x):p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
def norm(s):return ''.join(unicodedata.normalize('NFKC',s).split())
def alignment(a,b):
 a=norm(a);b=norm(b);dp=[[0]*(len(b)+1) for _ in range(len(a)+1)]
 for i in range(len(a)+1):dp[i][0]=i
 for j in range(len(b)+1):dp[0][j]=j
 for i in range(1,len(a)+1):
  for j in range(1,len(b)+1):dp[i][j]=min(dp[i-1][j]+1,dp[i][j-1]+1,dp[i-1][j-1]+(a[i-1]!=b[j-1]))
 i=len(a);j=len(b);counts={'correct':0,'substitutions':0,'deletions':0,'insertions':0}
 while i or j:
  if i and j and dp[i][j]==dp[i-1][j-1]+(a[i-1]!=b[j-1]):
   counts['correct' if a[i-1]==b[j-1] else 'substitutions']+=1;i-=1;j-=1
  elif i and dp[i][j]==dp[i-1][j]+1:counts['deletions']+=1;i-=1
  else:counts['insertions']+=1;j-=1
 return {**counts,'numerator':counts['correct'],'denominator':len(a),'value':counts['correct']/len(a) if a else None,'status':'measured' if a else 'not_measured','sample_ids':['native_synthetic_01'],'expected_normalized':a,'actual_normalized':b}
n=read(e/'native-result.json');assert hashlib.sha256((e/'native-input.png').read_bytes()).hexdigest()==n['input_sha256_before_ocr']
rows=[]
for result in n['results']:
 raw=result.get('raw') or {}; lines=raw.get('lines',[])
 primary=alignment('\n'.join(result['input_lines'][:3]),'\n'.join(x['text'] for x in lines if x.get('top',999)<250))
 whole=alignment('\n'.join(result['input_lines']),raw.get('fullText',''))
 names=['青青糯山无糖小杯','香辣鸡腿堡','奶油蛋糕30寸'];actual=[x['name'] for x in raw.get('dishes',[])]
 rows.append({'case_id':'native_synthetic_01','source_kind':'synthetic_image','run_kind':'native_ocr','platform':'synthetic','layout':'single_column_text','scenario_tags':['S03','S04','S05','S06'],'repeat':result['repeat'],'duration_ms':result['duration_ms'],'primary_text_recall':primary,'whole_text_recall':whole,'product_recall':{'numerator':sum(x in actual for x in names),'denominator':3,'value':sum(x in actual for x in names)/3,'status':'measured','sample_ids':['native_synthetic_01']},'error':result['error'],'actual':raw,'failure_note':'Marketing name character substitution retained as unknown; x vs multiplication sign counted as substitution under fixed normalization.'})
write(e/'native-case-results.json',rows)
m=read(e/'metrics.json');m['native']={'unique_images':1,'attempted':2,'run_kind':'native_ocr','source_kind':'synthetic_image','repeat_consistent':rows[0]['actual']==rows[1]['actual'],'cases':rows,'not_generalizable':'one authored image, no real platform coverage'};write(e/'metrics.json',m)
write(f/'native-manifest.json',{'dataset_version':'p4-synthetic-1','case_id':'native_synthetic_01','family_id':'p4_authored_order','source_kind':'synthetic_image','platform':'synthetic','layout':'single_column_text','split':'repair','source_note':'Canvas text generated by tool/p4_native_smoke.dart before native processing; no platform source','usage_basis':'developer authored','redaction_review':'no personal data or metadata','reviewer_status':'not_independently_reviewed','frozen_at':n['frozen_at_before_ocr'],'input_refs':[{'path':'dev-docs/p4-evidence/run-20260905/native-input.png','sha256':n['input_sha256_before_ocr'],'path_base':'repository'}],'annotations':n['results'][0]['input_lines'],'regions':{'primary':'first three lines, y<250','whole':'all four lines'},'normalization':'NFKC and whitespace only; x is not normalized to multiplication sign'})
print(json.dumps({'native_primary':rows[0]['primary_text_recall'],'native_products':rows[0]['product_recall'],'cleanup':{k:v for k,v in n.items() if 'exists' in k or 'preserved' in k}},ensure_ascii=False))
